Repository hapipal/schwifty, pull requests merged in 2019-12, with the labels that each got.

#74 Support objection v2
  API.md
  README.md
  package.json
Labels: dependency, enhancement

#78 Update links/references in docs
  API.md
  README.md
Labels: documentation

#76 Drop support for static models configuration
  API.md
  lib/index.js
  lib/schema.js
  test/index.js
  test/models/as-file.js
Labels: breaking changes

#79 Support joi v16
  API.md
  README.md
  lib/model.js
  package.json
  test/index.js
Labels: breaking changes, dependency, enhancement

#72 Use knex v0.16+ native migrator to support multiple directories
  API.md
  README.md
  lib/migrator.js
  package.json
  test/index.js
Labels: breaking changes, dependency

#82 Add tests for nested props and refs for field helper
  test/index.js
Labels: test

#81 Implement helper to extract per-field validation
  API.md
  lib/model.js
  test/index.js
Labels: enhancement
